package com.example.goldfinbudgeting.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// CategoryEntity maps to the categories table
// In this app, categories are the same as envelopes 
@Entity(tableName = "categories")
data class CategoryEntity(
    // Unique row id generated by Room on insert
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // Display name, like Groceries. expenses link to this via categoryName string
    val name: String,

    // Minimum monthly spending goal for this category
    val minGoal: Double,

    // Maximum monthly spending goal for this category 
    val maxGoal: Double,

    // Used to filter envelopes by month on the Envelopes screen
    val dateCreated: Long
)
