package com.example.goldfinbudgeting.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// ExpenseEntity maps to the "expenses" table
// Stores each expense entry
@Entity(tableName = "expenses")
data class ExpenseEntity(
    // Unique row id generated by Room on insert
    // Must use named args when constructing if id is omitted, because id is the first parameter
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // Short title shown in the expenses list 
    val name: String,

    // Money spent for this entry
    val amount: Double,

    // Category / envelope name this expense belongs to 
    // Kept as a string so existing Activities did not need a big rewrite
    val categoryName: String,

    // Date of the expense as epoch milliseconds 
    val dateCreated: Long,

    // Optional longer notes about the purchase
    val description: String = "",

    // Optional start time text from the expense form
    val startTime: String = "",

    // Optional end time text from the expense form
    val endTime: String = "",

    // The image file itself stays on disk; Room only stores the reference
    val receiptPath: String? = null
)
